name: Process Power Data

on:
  workflow_dispatch:
    inputs:
      json_file:
        description: 'MIDs .mbd build file'
        required: true
        type: file 

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/download-artifact@v3 
        with:
          name: power-data-artifact  
          path: /tmp/input_data        
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x' 
      - run: pip install -r requirements.txt 
      - run: python process_power.py /tmp/input_data/input.json -o /tmp/output.txt 
      - uses: actions/upload-artifact@v3 
        with:
          name: processed-data 
          path: /tmp/output.txt 
          retention-days: 1 # Adjust how long the file is available for download
