name: Process Power Data

on:
  workflow_dispatch:
    inputs:
      json_file:
        description: 'JSON file containing power data'
        required: true

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - uses: actions/upload-artifact@v4 
        with:
          name: power-data-artifact  
          path: uploaded_file.txt
      - uses: actions/download-artifact@v4 
        with:
          name: power-data-artifact  
          path: uploaded_file.txt 
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x' 
      - run: pip install -r requirements.txt 
      - run: python process_power.py /tmp/input_data/input.json -o /tmp/output.txt 
      - uses: actions/upload-artifact@v3 
        with:
          name: processed-data 
          path: /tmp/output.txt
          retention-days: 1
