name: Simple File Upload

on:
  workflow_dispatch:
    inputs:
      my_file: 
        description: 'The file to upload'
        required: true
        type: file

jobs:
  process_file: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls  # Check directory contents
      - uses: actions/upload-artifact@v3
        with:
          name: uploaded-file 
          path: uploaded_file.txt  
