name: Simple File Upload

on:
 workflow_dispatch:
    inputs:
      my_file: 
        description: 'The file to upload'
        required: true 
jobs:
  process_file: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls  # Check directory contents
      - uses: actions/upload-artifact@v4
        with:
          name: uploaded-file 
          path: uploaded_file.txt  
