name: Simple File Upload

on:
  workflow_dispatch:
    inputs:
      my_file: 
        description: 'The file to upload'
        required: true
        type: file

jobs:
  process_file:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: my_file 
          path: uploaded_file.txt  
